### ISSUE TITLE
6km 新宿から有楽町

### ISSUE THREAD

**Issue by trpfrog** [uec-walk/plan#19]

**Comment by Azuki-bar** [comment]
この徒歩会、ゆるゆるすぎますけどなんでできたんでしたっけ？

**Comment by trpfrog** [comment]
Discordに勝手にチャンネル立ってただけだから何も分からん……
Twitterで話進めてたとかなんです？

**Comment by minofumino** [comment]
新宿→有楽町ってイルミネーション徒歩会2021のときクリアしてない？

**Comment by trpfrog** [comment]
中止扱い？でcloseしてもよろしい？(完歩とも言えるが)

**Comment by Azuki-bar** [comment]
Closeで行きましょう
また生やせばいい
