### ISSUE TITLE
27km 調布から彩湖

### ISSUE THREAD

**Issue by trpfrog** [uec-walk/plan#38]
2022/03/29 (火)
午前8時 調布駅集合

## todo
- [x] ルート計画
- [x] 日程調整 

## 参加者
- @TrpFrog 
- @Azuki-bar 
- @minofumino 
- @kyu099 
- もっちゃん (Tw: sakuramochi0708)

## チェックポイント
- 深大寺
- 都立東伏見公園
- 練馬区立 大泉井頭公園
  - C3 まで川沿い
- C3徒歩会
- 彩湖
- 美女木JCT

**Comment by trpfrog** [comment]
大まかなルート
![2022-03-10_2 27 04](https://user-images.githubusercontent.com/7621012/160252135-aabd197b-d7a9-4f9c-b21a-0c9d9ba11a61.png)

**Comment by Azuki-bar** [comment]
参加者も書いておきませんか？

**Comment by trpfrog** [comment]
雨降りそうだけど決行、降ったら撤退

**Comment by trpfrog** [comment]
## 記録
- 2022/03/29
- 43.79km
- 62184歩

## ルート
![FPBOBRuVsAg11Iw](https://user-images.githubusercontent.com/7621012/160657982-ef366a4a-3ec0-4248-b777-c3e11c6381f8.jpg)
